[package]
name = "dex-info"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
reqwest = {version = "0.12.3", features = ["json"]}
serde_json = "1.0.115"
chrono = "0.4.38"
shuttle-actix-web = "0.49"
shuttle-runtime = "0.49"
tokio = "1"